### PR TITLE
drive tests with run-tests.

### PR DESCRIPTION
**Pull request by rainwoodman**
This is a demonstration.

Unfortunately I couldn't test this because pip install healpy failed
on my box with anaconda-5.0 cross compilation tools chain -- It couldn't link with cfitsio.

We need a good binary package of healpy.

#17

### CODE REVIEW

**Comment by rainwoodman** [comment]
The data files needs to be moved too for the tests to run due to the rename into pysm.test.

I am not sure about the best way of doing this.

```
(base) [yfeng1@waterfall PySM_public]$ python run-mpitests.py 
Purging /home/yfeng1/source/PySM_public/build/testenv ...
Purging /home/yfeng1/source/PySM_public/build/test ...
Building, see build.log...
Build OK
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/yfeng1/source/PySM_public, inifile:
plugins: hypothesis-3.38.5
collected 24 items

../testenv/lib/python3.6/site-packages/pysm/test/test_components.py .    [  4%]
../testenv/lib/python3.6/site-packages/pysm/test/test_common.py .        [  8%]
../testenv/lib/python3.6/site-packages/pysm/test/test_components.py .    [ 12%]
../testenv/lib/python3.6/site-packages/pysm/test/test_common.py .        [ 16%]
../testenv/lib/python3.6/site-packages/pysm/test/test_components.py F

=================================== FAILURES ===================================
__________________________ test_AME.test_AME_model_1 ___________________________

self = <pysm.test.test_components.test_AME testMethod=test_AME_model_1>

    def setUp(self):
        data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'pysm', 'template'))
        test_data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), 'test_data', 'benchmark'))
    
        a1_config = models("a1", 64)
        AME1 = components.AME(a1_config[0])
        AME2 = components.AME(a1_config[1])
    
        signal = lambda nu: AME1.signal()(nu) + AME2.signal()(nu)
    
>       ame_1_30GHz = read_map(os.path.join(test_data_dir, 'check3spinn_30p0_64.fits'), 64, field = (0, 1, 2))

../testenv/lib/python3.6/site-packages/pysm/test/test_components.py:148: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../testenv/lib/python3.6/site-packages/pysm/common.py:83: in read_map
    output_map = hp.ud_grade(hp.read_map(fname, field = field, verbose = verbose), nside_out = nside)
../../../../anaconda3/install/lib/python3.6/site-packages/healpy/fitsfunc.py:283: in read_map
    fits_hdu = _get_hdu(filename, hdu=hdu, memmap=memmap)
../../../../anaconda3/install/lib/python3.6/site-packages/healpy/fitsfunc.py:547: in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
../../../../anaconda3/install/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py:160: in fitsopen
    lazy_load_hdus, **kwargs)
../../../../anaconda3/install/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py:413: in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
../../../../anaconda3/install/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py:998: in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
../../../../anaconda3/install/lib/python3.6/site-packages/astropy/utils/decorators.py:507: in wrapper
    return function(*args, **kwargs)
../../../../anaconda3/install/lib/python3.6/site-packages/astropy/io/fits/file.py:150: in __init__
    self._open_filename(fileobj, mode, overwrite)
../../../../anaconda3/install/lib/python3.6/site-packages/astropy/io/fits/file.py:506: in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = '/home/yfeng1/source/PySM_public/build/testenv/lib/python3.6/site-packages/pysm/test/test_data/benchmark/check3spinn_30p0_64.fits'
mode = 'rb'

    def fileobj_open(filename, mode):
        """
            A wrapper around the `open()` builtin.
    
            This exists because in Python 3, `open()` returns an
            `io.BufferedReader` by default.  This is bad, because
            `io.BufferedReader` doesn't support random access, which we need in
            some cases.  In the Python 3 case (implemented in the py3compat module)
            we must call open with buffering=0 to get a raw random-access file
            reader.
            """
    
>       return open(filename, mode, buffering=0)
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/yfeng1/source/PySM_public/build/testenv/lib/python3.6/site-packages/pysm/test/test_data/benchmark/check3spinn_30p0_64.fits'

../../../../anaconda3/install/lib/python3.6/site-packages/astropy/io/fits/util.py:409: FileNotFoundError
=============================== warnings summary ===============================
build/testenv/lib/python3.6/site-packages/pysm/test/test_components.py::ComponentsTests::testBlack_Body
  /home/yfeng1/source/PySM_public/build/testenv/lib/python3.6/site-packages/pysm/test/test_components.py:20: AstropyDeprecationWarning: The blackbody_nu function is deprecated and may be removed in a future version.
          Use astropy.modeling.blackbody.blackbody_nu instead.
    astropy = blackbody_nu(90.e9, 100.) / blackbody_nu(30.e9, 100.)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
```

**Comment by zonca** [comment]
the healpy conda package doesn't work?

**Comment by rainwoodman** [comment]
You mean the one from conda-forge? Yes -- that's the one I tried, and it worked! Though it pulled in replacements a few unrelated packages (that's what I mean 'not clean'). 

I can fix the file not found error -- but it does seem the package contains some relatively big data files -- are they for testing only or are they necessary for the application to function? If they are for testing only perhaps a smaller version of file is preferred.

**Comment by zonca** [comment]
you can probably install mpi on travis with apt

**Comment by zonca** [comment]
with `sudo apt-get install -y -q openmpi-bin libopenmpi-dev`

**Comment by rainwoodman** [comment]
It is trickier. This is running on the docker based images, so we need to
use the apt add-on. I usually work with packages from anaconda; but I guess
you want to avoid that dependency in travis tests? If miniconda's OK I'll
just copy over the boilerplate we use everywhere else.

**Comment by zonca** [comment]
also everything from anaconda would be fine

**Comment by zonca** [comment]
anyway it looks like it is working fine now

**Comment by zonca** [comment]
@rainwoodman do you think this Pull Request is ready for @bthorne93 to review and merge?

**Comment by zonca** [comment]
I can then refactor #15 to use `runtests` as well

**Comment by rainwoodman** [comment]
Yes, please. Travis is finally green!

**Pull request merged**
