### PR TITLE
[WIP] Implementation of partial sky support

### PR DESCRIPTION
**Pull request by zonca**
Work In Progress

I am following #10 (thanks @bthorne93, your instructions were very clear!) to implement support for partial sky, for now I have implemented support in handling standard components, CMB and `hensley_draine_2017` Dust.

I am missing modifying what is related to the instrument, I'll work on that in the next days.

See partial sky support testing here (I can add the notebook to the repo once this is done): http://nbviewer.jupyter.org/gist/zonca/2ba1a145b150a73a427fd21b2ff82034

You can already start reviewing this as I go.

### CODE REVIEW

**Comment by zonca** [comment]
implemented support in `noiser`, missing just writing output maps

**Comment by zonca** [comment]
@bthorne93 I haven't finished yet, I'm working on the writing, can you please undo the merging?

**Comment by bthorne93** [comment]
@zonca okay, I've never had to undo a merge from a contributor's branch. Do you know how this is done via the web interface?

**Comment by bthorne93** [comment]
Okay, I think that's reverted it. Apologies!

**Pull request merged**
