### PR TITLE
MPI-enabled file access

### PR DESCRIPTION
**Pull request by zonca**
Work in progress, do not merge.

Add simple MPI capability to PySM:
Read all input files on rank 0 and then broadcast with `mpi4py` to other processes.

This is necessary for a run we'll be doing soon at NERSC with thousands of MPI processes.
I'll be improving this over the next week and let you know once it is ready for your review.

### CODE REVIEW

**Comment by zonca** [comment]
Some dust models are failing with this patch, need more debugging

**Comment by zonca** [comment]
@bthorne93 the Pull Request is ready to review.

I also added a `test_mpi.py` file that can be run with `mpirun -np 2 python test_mpi.py` to test MPI features,.

I also added a bugfix for an issue with dust being absent from a model, see 1f79e4a

**Comment by zonca** [comment]
@bthorne93 would you like to review this Pull Request?

**Comment by rainwoodman** [comment]
@zonca Looks like you're doing testing with MPI.
We coded our experience on MPI testing into https://github.com/bccp/runtests . It has been used in a large set of packages.

**Comment by zonca** [comment]
thanks @rainwoodman let's follow-up on https://github.com/bthorne93/PySM_public/issues/17

**Comment by zonca** [comment]
ok, `run-mpitests.py` is also testing the read_map functionality on Travis, see https://travis-ci.org/bthorne93/PySM_public/jobs/338058030#L627

@bthorne93 this is ready to review and merge

**Pull request merged**
